# `querexfuzz` project 

## Provenance
* Created new: 2025-08-27

In [1]:
%load_ext IPython.extensions.autoreload
%autoreload 2

from functools import partial
from pathlib import Path
from pprint import pprint
import logging 
import yaml 

def setup_logging(config_path):
    with config_path.open("r") as f:
        config = yaml.safe_load(f)
        logging.config.dictConfig(config)

setup_logging(Path("logconfig.yaml"))

from lark import Lark
import lark
import pandas as pd

from querexfuzz import Querexfuzz
from querexfuzz.parser import parser
import querexfuzz.parser as qfp
import querexfuzz.engine as qfe

In [7]:
parser('top 5 where year == 2025 and (name == joe or name == simon) @mod m-3:1')

10:58:35|ERROR |querexfuzz.parser[parser.py:267 parser] Failed to parse query: 'top 5 where year == 2025 and (name == joe or name == simon) @mod m-3:1.
Error: No terminal matches '(' in the current parser context, at line 1 col 30

top 5 where year == 2025 and (name == joe or name == simon) @mod m-3:
                             ^
Expected one of:
	* TILDE
	* IDENTIFIER

ValueError: Failed to parse query: 'top 5 where year == 2025 and (name == joe or name == simon) @mod m-3:1'. Error No terminal matches '(' in the current parser context, at line 1 col 30

top 5 where year == 2025 and (name == joe or name == simon) @mod m-3:
                             ^
Expected one of:
	* TILDE
	* IDENTIFIER

In [3]:
parser('top 10 top 20')

10:40:09|WARNING|querexfuzz.parser[parser.py:56 clause_list] re-setting top from 10 to 20

{'select': {'include': [], 'exclude': []},
 'sort': [],
 'regex': [],
 'where': None,
 'top': 20,
 'flags': [],
 'dates': [],
 'fuzzy': None}

# Pure parsing test

In [8]:
test_cases = {
 0: ('pass', '', ''),
 1: ('pass', '', '@ m'),
 2: ('pass', '', 'top 4 @ m-3'),
 3: ('fail', 'only integer time deltas', 'recent select m, y, q @ y-3:1.234'),
 4: ('pass', '', 'recent top 3 @ m'),
 5: ('pass', '', 'verbose recent top 17 @COL d-30:10 @MOD m-3'),
 6: ('pass', '', 'select roger'),
 7: ('pass', '', 'select a_col'),
 8: ('pass', '', 'select a_col2, b_col'),
 9: ('pass', '', 'select *'),
 10: ('pass', '', 'top 10 select *'),
 11: ('pass', '', 'where year == 2024'),
 12: ('pass', '', 'where year == "2024"'),
 13: ('pass', '', 'where type == "book"'),
 14: ('pass', '', 'where price <= 12.50'),
 15: ('pass', '', '! Delbaen'),
 16: ('pass', '', '! /Wang, R/ and journal ~ Annals'),
 17: ('pass', '', 'recent top 3 author ~ /Wang, R/'),
 18: ('pass', '', 'select journal author ~ /Wang, R/'),
 19: ('pass', '', 'verbose top 4 recent select journal author ~ /Wang, R/'),
 20: ('pass', '', 'top 5 select journal author ~ /Wang, R/'),
 21: ('pass', '', 'sort by journal'),
 22: ('pass', '', 'order by journal, -year'),
 23: ('pass', '', 'order by journal, -year'),
 24: ('pass', 'changing top ok but warning', 'top 6 top 26 sort by journal'),
 25: ('pass', '', 'top 7 sort by -journal'),
 26: ('pass', '', 'top 8 order by author, journal, year'),
 27: ('pass', '', 'top 9 select journal where year == 2024 order by author'),
 28: ('pass',
      '',
      'verbose top 10 select journal where year == 2024 order by -journal, '
      'author'),
 29: ('pass',
      '',
      'recent top 14  verbose select *, -c ! /Wang, R/ and journal ~ /[A-J]+/ '
      'where year == 2024 and publisher ==  "Springer" and mod > 2024'),
 30: ('pass',
      '',
      'recent top 15  verbose select *, -c ! /Wang, R/ and journal ~ [A-J]+ '
      'where year == 2024 and publisher ==  "Springer" and mod > "2024-05"'),
 31: ('pass',
      '',
      'recent top 20  verbose select *, -c ! /Wang, R/ and journal ~ [A-J]+ '
      'where year == 2024 and publisher ==  "Springer" and mod > 2024-05'),
 32: ('pass',
      '',
      'recent top 21  verbose select *, -c ! /Wang, R/ and journal ~ [A-J]+ '
      'where year == 2024 and publisher ==  "Springer" and mod > "2024-05"'),
 33: ('pass',
      '',
      'top 30 select c, d, -a, e recent ! /Wang, R/ and journal ~ [A-J]+ where '
      'year == 2024 and publisher ==  "Springer" and mod > 2024 order by name, '
      'year'),
 34: ('fail', 'obvious error', 'error'),
 35: ('pass',
      '',
      'top 40 recent where age > 30 name ~ /^A/  @ y # alice amsterdam'),
 36: ('pass', '', 'recent top 50 where author == "Wang" !Ruodu # fuzzy term'),
 37: ('pass',
      'odd order',
      'where price > 10.5 select *, -id top 20 order by price'),
 38: ('pass',
      'odd order',
      'order by -modified, created verbose recent select path where size > '
      '1000'),
 39: ('pass',
      'odd order',
      "select name, id recent where type == 'user' top 50"),
 40: ('pass',
      'odd order, unquoted regex',
      'author ~ Smith order by name select *'),
 41: ('pass', 'cols vs keywords', 'select top, order, by, where, select'),
 42: ('pass',
      'cols vs keywords',
      'where top == 1 and sort == "asc" and by == "user"'),
 43: ('pass', 'cols vs keywords', 'select y, m, d, h order by q'),
 44: ('pass', 'cols vs keywords', 'where year > y and month > m'),
 45: ('pass',
      'complex where, regex, date',
      'where price >= -99.5 and price <= 21.25 and category != "sale" and name == "a name with '
      'spaces"'),
 46: ('pass',
      'complex where, regex, date',
      'where start_date > end_date and value > 0'),
 47: ('pass',
      'complex where, regex, date',
      '! /A/ and author ~ /B/ and title ~ /C/ and journal ~ /D/'),
 48: ('pass',
      'complex where, regex, date',
      '@created q-1 @modified w-2 @accessed d-3 @expires h-4'),
 49: ('pass',
      'complex where, regex, date',
      'select id, -name, created, -updated, path order by -created, path'),
 50: ('pass',
      'formatting, minimal',
      ' \t top   10 \n   select name, id \n where \t year==2025'),
 51: ('pass', 'formatting, minimal', '# just a fuzzy search string by itself'),
 52: ('pass', 'formatting, minimal', 'select name order by name'),
 53: ('pass', 'formatting, minimal', '@ d-0'),
 54: ('fail', 'single =', 'where value = 5'),
 55: ('fail', 'keyword for identifier', 'select name, where type == "book"'),
 56: ('fail', 'trailing comma', 'top 10 order by name,'),
 57: ('fail', 'non-numeric', '@ m-5:foo')}

In [10]:
x = 10 
f'asdf {
x}'

'asdf 10'

In [21]:
parser('top 5 where year == 2025 or name == joe @mod m-3:1')

10:39:23|INFO  |querexfuzz.parser[parser.py:19 <module>] built parser.py
10:39:24|ERROR |querexfuzz.parser[parser.py:274 parser] Failed to Transform: 'top 5 where year == 2025 or name == joe @mod m-3:1'.
Error:
Error trying to process rule "where_clause_list":

tuple index out of range

ValueError: Failed to transform query: 'top 5 where year == 2025 or name == joe @mod m-3:1'. Error: Error trying to process rule "where_clause_list":

tuple index out of range

In [12]:
def run_tests(parser, test_dict, verbose=True):
    """
    Run parser tests on test_dict.

    test_dict = { (n, desc) -> test}
    
    """
    success = fail =  0
    for n, (expected, desc, query) in test_dict.items(): 
        try:
            if verbose: print(f"Query No. {n}\n{desc}")
            if verbose: print(f'{query = }\n')
            spec_dict = parser(query)
        except Exception as e:
            fail += 1
            if verbose or expected != 'fail':
                print(f'result: fail ({expected} expected) for query {n}: {query}')
        else:
            success += 1
            if verbose or expected != 'pass': 
                print(f'result: pass ({expected})\n')
            if verbose: pprint(spec_dict)
        if verbose: print('-'*40, end='\n\n')
    es = sum(i[0]=='pass' for i in test_dict.values())
    ef = len(test_dict) - es
    print(f'''
    SUMMARY:
    Pass    {success} vs expected {es}
    Fail    {fail} vs expected {ef}
    Total   {success+fail}
    Pct     {success / (success+fail):.0%}
    ''')

In [13]:
run_tests(parser, test_cases, False)

    SUMMARY:
    Pass    52 vs expected 52
    Fail    6 vs expected 6
    Total   58
    Pct     90%

In [14]:
run_tests(parser, test_cases, True)

Query No. 0

query = ''

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 1

query = '@ m'

result: pass (pass)

{'dates': [{'end': 0, 'field': None, 'start': 1, 'unit': 'm'}],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 2

query = 'top 4 @ m-3'

result: pass (pass)

{'dates': [{'end': '0', 'field': None, 'start': 3, 'unit': 'm'}],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': 4,
 'where': None}
----------------------------------------

Query No. 3
only integer time deltas
query = 'recent select m, y, q @ y-3:1.234'

result: fail (fail expected) for query 3: recent select m, y, q @ y-3:1.234
----------------------------------------

Query No. 4

query = 'recent top 3 @ m'

result: pass (pass)

{'dates': [{'end': 0, 'field': None, 'start': 1, 'unit': 'm'}],
 'flags': ['recent'],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': 3,
 'where': None}
----------------------------------------

Query No. 5

query = 'verbose recent top 17 @COL d-30:10 @MOD m-3'

result: pass (pass)

{'dates': [{'end': 10, 'field': 'COL', 'start': 30, 'unit': 'd'},
           {'end': '0', 'field': 'MOD', 'start': 3, 'unit': 'm'}],
 'flags': ['verbose', 'recent'],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': 17,
 'where': None}
----------------------------------------

Query No. 6

query = 'select roger'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': ['roger']},
 'sort': [],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 7

query = 'select a_col'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': ['a_col']},
 'sort': [],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 8

query = 'select a_col2, b_col'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': ['a_col2', 'b_col']},
 'sort': [],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 9

query = 'select *'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': ['all']},
 'sort': [],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 10

query = 'top 10 select *'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': ['all']},
 'sort': [],
 'top': 10,
 'where': None}
----------------------------------------

Query No. 11

query = 'where year == 2024'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': -1,
 'where': 'year == 2024'}
----------------------------------------

Query No. 12

query = 'where year == "2024"'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': -1,
 'where': 'year == "2024"'}
----------------------------------------

Query No. 13

query = 'where type == "book"'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': -1,
 'where': 'type == "book"'}
----------------------------------------

Query No. 14

query = 'where price <= 12.50'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': -1,
 'where': 'price <= 12.50'}
----------------------------------------

Query No. 15

query = '! Delbaen'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [[('BANG', 'Delbaen')]],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 16

query = '! /Wang, R/ and journal ~ Annals'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [[('BANG', 'Wang, R'), ('journal', 'Annals')]],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 17

query = 'recent top 3 author ~ /Wang, R/'

result: pass (pass)

{'dates': [],
 'flags': ['recent'],
 'fuzzy': None,
 'regex': [[('author', 'Wang, R')]],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': 3,
 'where': None}
----------------------------------------

Query No. 18

query = 'select journal author ~ /Wang, R/'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [[('author', 'Wang, R')]],
 'select': {'exclude': [], 'include': ['journal']},
 'sort': [],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 19

query = 'verbose top 4 recent select journal author ~ /Wang, R/'

result: pass (pass)

{'dates': [],
 'flags': ['verbose', 'recent'],
 'fuzzy': None,
 'regex': [[('author', 'Wang, R')]],
 'select': {'exclude': [], 'include': ['journal']},
 'sort': [],
 'top': 4,
 'where': None}
----------------------------------------

Query No. 20

query = 'top 5 select journal author ~ /Wang, R/'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [[('author', 'Wang, R')]],
 'select': {'exclude': [], 'include': ['journal']},
 'sort': [],
 'top': 5,
 'where': None}
----------------------------------------

Query No. 21

query = 'sort by journal'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [('journal', True)],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 22

query = 'order by journal, -year'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [('journal', True), ('year', False)],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 23

query = 'order by journal, -year'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [('journal', True), ('year', False)],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 24

query = 'top 6 sort by journal'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [('journal', True)],
 'top': 6,
 'where': None}
----------------------------------------

Query No. 25

query = 'top 7 sort by -journal'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [('journal', False)],
 'top': 7,
 'where': None}
----------------------------------------

Query No. 26

query = 'top 8 order by author, journal, year'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [('author', True), ('journal', True), ('year', True)],
 'top': 8,
 'where': None}
----------------------------------------

Query No. 27

query = 'top 9 select journal where year == 2024 order by author'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': ['journal']},
 'sort': [('author', True)],
 'top': 9,
 'where': 'year == 2024'}
----------------------------------------

Query No. 28

query = 'verbose top 10 select journal where year == 2024 order by -journal, author'

result: pass (pass)

{'dates': [],
 'flags': ['verbose'],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': ['journal']},
 'sort': [('journal', False), ('author', True)],
 'top': 10,
 'where': 'year == 2024'}
----------------------------------------

Query No. 29

query = 'recent top 14  verbose select *, -c ! /Wang, R/ and journal ~ /[A-J]+/ where year == 2024 and publisher ==  "Springer" and mod > 2024'

result: pass (pass)

{'dates': [],
 'flags': ['recent', 'verbose'],
 'fuzzy': None,
 'regex': [[('BANG', 'Wang, R'), ('journal', '[A-J]+')]],
 'select': {'exclude': ['c'], 'include': ['all']},
 'sort': [],
 'top': 14,
 'where': 'year == 2024 and publisher == "Springer" and mod > 2024'}
----------------------------------------

Query No. 30

query = 'recent top 15  verbose select *, -c ! /Wang, R/ and journal ~ [A-J]+ where year == 2024 and publisher ==  "Springer" and mod > "2024-05"'

result: pass (pass)

{'dates': [],
 'flags': ['recent', 'verbose'],
 'fuzzy': None,
 'regex': [[('BANG', 'Wang, R'), ('journal', '[A-J]+')]],
 'select': {'exclude': ['c'], 'include': ['all']},
 'sort': [],
 'top': 15,
 'where': 'year == 2024 and publisher == "Springer" and mod > "2024-05"'}
----------------------------------------

Query No. 31

query = 'recent top 20  verbose select *, -c ! /Wang, R/ and journal ~ [A-J]+ where year == 2024 and publisher ==  "Springer" and mod > 2024-05'

result: pass (pass)

{'dates': [],
 'flags': ['recent', 'verbose'],
 'fuzzy': None,
 'regex': [[('BANG', 'Wang, R'), ('journal', '[A-J]+')]],
 'select': {'exclude': ['c'], 'include': ['all']},
 'sort': [],
 'top': 20,
 'where': 'year == 2024 and publisher == "Springer" and mod > 2024-05'}
----------------------------------------

Query No. 32

query = 'recent top 21  verbose select *, -c ! /Wang, R/ and journal ~ [A-J]+ where year == 2024 and publisher ==  "Springer" and mod > "2024-05"'

result: pass (pass)

{'dates': [],
 'flags': ['recent', 'verbose'],
 'fuzzy': None,
 'regex': [[('BANG', 'Wang, R'), ('journal', '[A-J]+')]],
 'select': {'exclude': ['c'], 'include': ['all']},
 'sort': [],
 'top': 21,
 'where': 'year == 2024 and publisher == "Springer" and mod > "2024-05"'}
----------------------------------------

Query No. 33

query = 'top 30 select c, d, -a, e recent ! /Wang, R/ and journal ~ [A-J]+ where year == 2024 and publisher ==  "Springer" and mod > 2024 order by name, year'

result: pass (pass)

{'dates': [],
 'flags': ['recent'],
 'fuzzy': None,
 'regex': [[('BANG', 'Wang, R'), ('journal', '[A-J]+')]],
 'select': {'exclude': ['a'], 'include': ['c', 'd', 'e']},
 'sort': [('name', True), ('year', True)],
 'top': 30,
 'where': 'year == 2024 and publisher == "Springer" and mod > 2024'}
----------------------------------------

Query No. 34
obvious error
query = 'error'

result: fail (fail expected) for query 34: error
----------------------------------------

Query No. 35

query = 'top 40 recent where age > 30 name ~ /^A/  @ y # alice amsterdam'

result: pass (pass)

{'dates': [{'end': 0, 'field': None, 'start': 1, 'unit': 'y'}],
 'flags': ['recent'],
 'fuzzy': 'alice amsterdam',
 'regex': [[('name', '^A')]],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': 40,
 'where': 'age > 30'}
----------------------------------------

Query No. 36

query = 'recent top 50 where author == "Wang" !Ruodu # fuzzy term'

result: pass (pass)

{'dates': [],
 'flags': ['recent'],
 'fuzzy': 'fuzzy term',
 'regex': [[('BANG', 'Ruodu')]],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': 50,
 'where': 'author == "Wang"'}
----------------------------------------

Query No. 37
odd order
query = 'where price > 10.5 select *, -id top 20 order by price'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': ['id'], 'include': ['all']},
 'sort': [('price', True)],
 'top': 20,
 'where': 'price > 10.5'}
----------------------------------------

Query No. 38
odd order
query = 'order by -modified, created verbose recent select path where size > 1000'

result: pass (pass)

{'dates': [],
 'flags': ['verbose', 'recent'],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': ['path']},
 'sort': [('modified', False), ('created', True)],
 'top': -1,
 'where': 'size > 1000'}
----------------------------------------

Query No. 39
odd order
query = "select name, id recent where type == 'user' top 50"

result: pass (pass)

{'dates': [],
 'flags': ['recent'],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': ['name', 'id']},
 'sort': [],
 'top': 50,
 'where': "type == 'user'"}
----------------------------------------

Query No. 40
odd order, unquoted regex
query = 'author ~ Smith order by name select *'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [[('author', 'Smith')]],
 'select': {'exclude': [], 'include': ['all']},
 'sort': [('name', True)],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 41
cols vs keywords
query = 'select top, order, by, where, select'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [],
            'include': ['top', 'order', 'by', 'where', 'select']},
 'sort': [],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 42
cols vs keywords
query = 'where top == 1 and sort == "asc" and by == "user"'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': -1,
 'where': 'top == 1 and sort == "asc" and by == "user"'}
----------------------------------------

Query No. 43
cols vs keywords
query = 'select y, m, d, h order by q'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': ['y', 'm', 'd', 'h']},
 'sort': [('q', True)],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 44
cols vs keywords
query = 'where year > y and month > m'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': -1,
 'where': 'year > y and month > m'}
----------------------------------------

Query No. 45
complex where, regex, date
query = 'where price >= -99.5 and price <= 21.25 and category != "sale" and name == "a name with spaces"'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': -1,
 'where': 'price >= -99.5 and price <= 21.25 and category != "sale" and name '
          '== "a name with spaces"'}
----------------------------------------

Query No. 46
complex where, regex, date
query = 'where start_date > end_date and value > 0'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': -1,
 'where': 'start_date > end_date and value > 0'}
----------------------------------------

Query No. 47
complex where, regex, date
query = '! /A/ and author ~ /B/ and title ~ /C/ and journal ~ /D/'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [[('BANG', 'A'), ('author', 'B'), ('title', 'C'), ('journal', 'D')]],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 48
complex where, regex, date
query = '@created q-1 @modified w-2 @accessed d-3 @expires h-4'

result: pass (pass)

{'dates': [{'end': '0', 'field': 'created', 'start': 1, 'unit': 'q'},
           {'end': '0', 'field': 'modified', 'start': 2, 'unit': 'w'},
           {'end': '0', 'field': 'accessed', 'start': 3, 'unit': 'd'},
           {'end': '0', 'field': 'expires', 'start': 4, 'unit': 'h'}],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 49
complex where, regex, date
query = 'select id, -name, created, -updated, path order by -created, path'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': ['name', 'updated'],
            'include': ['id', 'created', 'path']},
 'sort': [('created', False), ('path', True)],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 50
formatting, minimal
query = ' \t top   10 \n   select name, id \n where \t year==2025'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': ['name', 'id']},
 'sort': [],
 'top': 10,
 'where': 'year == 2025'}
----------------------------------------

Query No. 51
formatting, minimal
query = '# just a fuzzy search string by itself'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': 'just a fuzzy search string by itself',
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 52
formatting, minimal
query = 'select name order by name'

result: pass (pass)

{'dates': [],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': ['name']},
 'sort': [('name', True)],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 53
formatting, minimal
query = '@ d-0'

result: pass (pass)

{'dates': [{'end': '0', 'field': None, 'start': 0, 'unit': 'd'}],
 'flags': [],
 'fuzzy': None,
 'regex': [],
 'select': {'exclude': [], 'include': []},
 'sort': [],
 'top': -1,
 'where': None}
----------------------------------------

Query No. 54
single =
query = 'where value = 5'

result: fail (fail expected) for query 54: where value = 5
----------------------------------------

Query No. 55
keyword for identifier
query = 'select name, where type == "book"'

result: fail (fail expected) for query 55: select name, where type == "book"
----------------------------------------

Query No. 56
trailing comma
query = 'top 10 order by name,'

result: fail (fail expected) for query 56: top 10 order by name,
----------------------------------------

Query No. 57
non-numeric
query = '@ m-5:foo'

result: fail (fail expected) for query 57: @ m-5:foo
----------------------------------------


    SUMMARY:
    Pass    52 vs expected 52
    Fail    6 vs expected 6
    Total   58
    Pct     90%

In [15]:
# parser(test_cases[45][2])
parser('where price >= -99.5')

{'select': {'include': [], 'exclude': []},
 'sort': [],
 'regex': [],
 'where': 'price >= -99.5',
 'top': -1,
 'flags': [],
 'dates': [],
 'fuzzy': None}

In [19]:
parser(" ! /[ae]{2,}/ and version ~ [a-e]{5} ")

{'select': {'include': [], 'exclude': []},
 'sort': [],
 'regex': [('BANG', '[ae]{2,}'), ('version', '[a-e]{5}')],
 'where': None,
 'top': -1,
 'flags': [],
 'dates': [],
 'fuzzy': None}

# Simple example

In [20]:
# 1. Create a sample DataFrame
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'age': [25, 30, 35, 40, 45],
    'city': ['Amsterdam', 'Berlin', 'Copenhagen', 'Berlin', 'Amsterdam'],
    'registered_date': pd.to_datetime(['2025-08-10', '2025-06-15', '2024-01-20', '2025-08-25', '2025-07-30'])
}
df = pd.DataFrame(data)
df

      name  age        city registered_date
0    Alice   25   Amsterdam      2025-08-10
1      Bob   30      Berlin      2025-06-15
2  Charlie   35  Copenhagen      2024-01-20
3    David   40      Berlin      2025-08-25
4      Eve   45   Amsterdam      2025-07-30

In [21]:
# 2. Initialize Querexfuzz with your config file
# (Ensure config.yml is in the same directory or provide the correct path)
qflex_engine = Querexfuzz(config_path='config.yaml')

In [22]:
qflex_engine.config

QuerexfuzzConfig(base_cols=['name', 'city', 'registered_date', 'age'], date_fields=['registered_date'], default_date_field='registered_date', bang_field='name', recent_field='registered_date', fuzzy=FuzzyConfig(fields=['name', 'city'], limit=50, score_col_name='score'))

In [23]:
# 3. Attach the .querexfuzz method to your DataFrame
df = qflex_engine.attach_to(df)

In [24]:
# 4. Run queries!
print("--- People from Berlin ---")
df.querexfuzz("where city == 'Berlin'")

--- People from Berlin ---

    name    city registered_date  age
1    Bob  Berlin      2025-06-15   30
3  David  Berlin      2025-08-25   40

In [25]:
print("\n--- Recently registered (last 1 month) ---")
df.querexfuzz("recent @m-1")

--- Recently registered (last 1 month) ---

    name       city registered_date  age
3  David     Berlin      2025-08-25   40
0  Alice  Amsterdam      2025-08-10   25
4    Eve  Amsterdam      2025-07-30   45

In [27]:
# same without number
df.querexfuzz("recent @m")

    name       city registered_date  age
3  David     Berlin      2025-08-25   40
0  Alice  Amsterdam      2025-08-10   25
4    Eve  Amsterdam      2025-07-30   45

In [29]:
print("\n--- Less recently registered (last 24 months but more than 4) ---")
df.querexfuzz("recent @m-24:4")

--- Less recently registered (last 24 months but more than 4) ---

      name        city registered_date  age
2  Charlie  Copenhagen      2024-01-20   35

In [30]:
print("\n--- Fuzzy search for 'am', sorted by score ---")
df.querexfuzz("# am")

--- Fuzzy search for 'am', sorted by score ---

    name       city registered_date  age
4    Eve  Amsterdam      2025-07-30   45
0  Alice  Amsterdam      2025-08-10   25

In [31]:
print("\n--- Complex query: top 1 from Berlin older than 35, select name and age ---")
df.querexfuzz("top 1 where city == 'Berlin' and age > 35 select name, age")

--- Complex query: top 1 from Berlin older than 35, select name and age ---

    name    city registered_date  age
3  David  Berlin      2025-08-25   40

In [39]:
print("\n--- Bang query: names with a and e ! /[ae]{2,}/ ---")
df.querexfuzz(" ! [ae].*[ae]  ")

--- Bang query: names with a and e ! /[ae]{2,}/ ---

      name        city registered_date  age
0    Alice   Amsterdam      2025-08-10   25
2  Charlie  Copenhagen      2024-01-20   35
4      Eve   Amsterdam      2025-07-30   45

In [33]:
df

      name  age        city registered_date
0    Alice   25   Amsterdam      2025-08-10
1      Bob   30      Berlin      2025-06-15
2  Charlie   35  Copenhagen      2024-01-20
3    David   40      Berlin      2025-08-25
4      Eve   45   Amsterdam      2025-07-30

# Better test dataframes

In [42]:
from greater_tables.core import GT
from greater_tables.fabrications import quick_fab
fGT = partial(GT, large_ok=True)

In [61]:
testdf = quick_fab(rows=10, data_spec='ss3fid', 
                   # metric_name_spec='s3'*5,
                   metric_name_spec=['name', 'address', 'size', 'number', 'registered_date']
                  )
fGT(testdf)

GT(df_id=TOGOPWNRYJTYH)

In [62]:
q = Querexfuzz('config.yaml')
q.config

QuerexfuzzConfig(base_cols=['name', 'city', 'registered_date', 'age'], date_fields=['registered_date'], default_date_field='registered_date', bang_field='name', recent_field='registered_date', fuzzy=FuzzyConfig(fields=['name', 'city'], limit=50, score_col_name='score'))

In [66]:
testdf = q.attach_to(testdf)
testdf

metric,name,address,size,number,registered_date
i_0,,,,,
genuine,hydro,shamrock paragraph jungle,-155377.890829,675489,2015-12-27 22:22:10.823910
characterize,deafness,breathed gift foreman,315701.664315,268625,2015-12-28 22:22:10.823910
descriptive,malady,arcade administered commendable,-91991.698973,600497,2015-12-29 22:22:10.823910
property,substitution,kilobytes modestly matches,-50750.058161,160307,2015-12-30 22:22:10.823910
role,gloomy,puppet transformational ensures,134758.486135,55814,2015-12-31 22:22:10.823910
goods,siemens,wretched knight albatross,-9030.709577,317549,2016-01-01 22:22:10.823910
reel,therapist,surrounding physics endless,222803.713561,879182,2016-01-02 22:22:10.823910
escalation,pleased,denunciation defendants replica,45805.338369,85443,2016-01-03 22:22:10.823910
physically,define,crates stalks dispels,-26050.642093,18031,2016-01-04 22:22:10.823910
involved,steaks,turnout priorities waster,707895.422246,532800,2016-01-05 22:22:10.823910

In [76]:
df.querexfuzz(" ! ice") #  "name ~ ^[A-B]")

    name       city registered_date  age
0  Alice  Amsterdam      2025-08-10   25

In [78]:
df

      name  age        city registered_date
0    Alice   25   Amsterdam      2025-08-10
1      Bob   30      Berlin      2025-06-15
2  Charlie   35  Copenhagen      2024-01-20
3    David   40      Berlin      2025-08-25
4      Eve   45   Amsterdam      2025-07-30

In [79]:
df.querexfuzz("@registered_date m-28:6")

      name        city registered_date  age
2  Charlie  Copenhagen      2024-01-20   35

In [80]:
testdf.querexfuzz('# Berlin')

Empty DataFrame
Columns: [name, registered_date]
Index: []

In [71]:
testdf.querexfuzz('select all where number < 800000 and number > 500000')

metric         name            registered_date
i_0
genuine       hydro 2015-12-27 22:22:10.823910
descriptive  malady 2015-12-29 22:22:10.823910
involved     steaks 2016-01-05 22:22:10.823910

In [72]:
testdf.querexfuzz(' ! ^[hdm] ')

metric            name            registered_date
i_0
genuine          hydro 2015-12-27 22:22:10.823910
characterize  deafness 2015-12-28 22:22:10.823910
descriptive     malady 2015-12-29 22:22:10.823910
physically      define 2016-01-04 22:22:10.823910

In [81]:
from rustfuzz import FuzzyMatcherMultiHi

In [83]:
FuzzyMatcherMultiHi?

Init signature: FuzzyMatcherMultiHi(strings, /)
Docstring:
A multi-word fuzzy matcher that returns highlighting information.

Similar to `FuzzyMatcherMulti`, but the query method returns an additional
list containing the specific character indices that matched the query,
suitable for highlighting in a UI.
Type:           type
Subclasses:

In [84]:
FuzzyMatcherMultiHi.query?

Signature: FuzzyMatcherMultiHi.query(self, query, top_k, /)
Docstring:
Finds the best fuzzy matches and returns their highlight indices.

Args:
    query (str): The search query, with words separated by spaces.
    top_k (int): The maximum number of results to return.

Returns:
    tuple[list[int], list[int], list[list[int]]]: A tuple containing three lists:
        - A list of indices of the matched strings.
        - A list of the corresponding scores.
        - A list of lists, where each inner list contains the character
          indices to highlight for that match.
Type:      method_descriptor

In [82]:
# 1. Define your list of candidate strings
candidates = [
    "A Case Study in Causal Inference",
    "Advanced Causality: Theory and Practice",
    "rust-analyzer: a language server for Rust",
    "The Rust Programming Language",
    "Practical Time-Series Analysis",
]

# 2. Create a matcher instance
matcher = FuzzyMatcherMultiHi(candidates)

In [85]:
# 3. Run a query
query_str = "rust lang"
indices, scores, highlights = matcher.query(query_str, top_k=2)
indices, scores, highlights

([2, 3],
 [174, 162],
 [[0, 1, 2, 3, 17, 18, 19, 20], [4, 5, 6, 7, 21, 22, 23, 24]])

In [90]:
# 4. Process the results
print(f"Top {len(indices)} results for query: '{query_str}'\n")

for i, score, highlight_indices in zip(indices, scores, highlights):
    candidate_string = candidates[i]

    # Use the highlight indices to format the output (e.g., for HTML)
    highlight_set = set(highlight_indices)

    highlighted_html = "".join(
        f"<mark>{char}</mark>" if i in highlight_set else char
        for i, char in enumerate(candidate_string)
    )
    highlighted_html = highlighted_html.replace("</mark><mark>", "")
    print(f"Score: {score}")
    print(f"  - Original:    '{candidate_string}'")
    print(f"  - Highlighted: {highlighted_html}\n")

Top 2 results for query: 'rust lang'

Score: 174
  - Original:    'rust-analyzer: a language server for Rust'
  - Highlighted: <mark>rust</mark>-analyzer: a <mark>lang</mark>uage server for Rust

Score: 162
  - Original:    'The Rust Programming Language'
  - Highlighted: The <mark>Rust</mark> Programming <mark>Lang</mark>uage

In [88]:
from IPython.display import HTML, display

In [91]:
display(HTML(highlighted_html))

In [ ]:
```

**Expected Output:**

```text
Top 2 results for query: 'rust lang'

Score: 308
  - Original:    'The Rust Programming Language'
  - Highlighted: The <mark>Rust</mark> Programming <mark>Lang</mark>uage

Score: 194
  - Original:    'rust-analyzer: a language server for Rust'
  - Highlighted: <mark>rust</mark>-analyzer: a <mark>lang</mark>uage server for Rust
```

-----

In [92]:
testdf = quick_fab(rows=10000, data_spec='ss20fid', 
                   # metric_name_spec='s3'*5,
                   metric_name_spec=['name', 'address', 'size', 'number', 'registered_date']
                  )
fGT(testdf.head())

GT(df_id=TSGITSFROI7DK)

In [93]:
q = Querexfuzz('config.yaml')
q.config

QuerexfuzzConfig(base_cols=['name', 'city', 'registered_date', 'age'], date_fields=['registered_date'], default_date_field='registered_date', bang_field='name', recent_field='registered_date', fuzzy=FuzzyConfig(fields=['name', 'city'], limit=50, score_col_name='score'))

In [95]:
testdf = q.attach_to(testdf)
testdf.head()

metric,name,address,size,number,registered_date
i_0,,,,,
decaying,indexer,dedicate apaches cans mission cordially expedi...,583334.701109,475885,2024-11-06 09:00:53.974223
dismay,sniff,vaunted scientists risky welsh underlying infl...,456941.167486,527237,2024-11-07 09:00:53.974223
erections,categorizing,decouple gargantuan adjudicating twirling maci...,160335.668631,71729,2024-11-08 09:00:53.974223
repudiate,assertions,accelerator tango writes plunger machinations ...,284940.487070,441815,2024-11-09 09:00:53.974223
shah,grinch,registering suffices leanest natured center de...,-17454.904663,982356,2024-11-10 09:00:53.974223

In [102]:
fGT(testdf.loc[testdf.querexfuzz('address ~ \\brisky\\b').index])

GT(df_id=TAGDQ3EGU2ZPV)

In [ ]:
testdf.loc[testdf.querexfuzz('top 10 # risky').index]