# `querexfuzz` project 

## Provenance
* Created new: 2025-08-27

In [7]:
%load_ext IPython.extensions.autoreload
%autoreload 2

from functools import partial
from pathlib import Path
from pprint import pprint
import logging 
import yaml 

def setup_logging(config_path):
    with config_path.open("r") as f:
        config = yaml.safe_load(f)
        logging.config.dictConfig(config)

setup_logging(Path("logconfig.yaml"))

from lark import Lark
import lark
import pandas as pd

from querexfuzz import Querexfuzz
from querexfuzz.parser import parser
import querexfuzz.parser as qfp
import querexfuzz.engine as qfe

16:53:21.935|INFO  |querexfuzz.parser[parser.py:19 <module>] built parser.py

The IPython.extensions.autoreload extension is already loaded. To reload it, use:
  %reload_ext IPython.extensions.autoreload

In [8]:
parser('top 5 where year == 2025 and (name == joe or name == simon) @mod m-3:1')

16:53:24.217|ERROR |querexfuzz.parser[parser.py:267 parser] Failed to parse query: 'top 5 where year == 2025 and (name == joe or name == simon) @mod m-3:1.
Error: No terminal matches '(' in the current parser context, at line 1 col 30

top 5 where year == 2025 and (name == joe or name == simon) @mod m-3:
                             ^
Expected one of:
	* TILDE
	* IDENTIFIER

ValueError: Failed to parse query: 'top 5 where year == 2025 and (name == joe or name == simon) @mod m-3:1'. Error No terminal matches '(' in the current parser context, at line 1 col 30

top 5 where year == 2025 and (name == joe or name == simon) @mod m-3:
                             ^
Expected one of:
	* TILDE
	* IDENTIFIER

In [9]:
parser('top 10 top 20')

{'select': {'include': [], 'exclude': []},
 'sort': [],
 'regex': [],
 'where': None,
 'top': 20,
 'flags': [],
 'dates': [],
 'fuzzy': None}

# Pure parsing test

In [10]:
test_cases = {
 0: ('pass', '', ''),
 1: ('pass', '', '@ m'),
 2: ('pass', '', 'top 4 @ m-3'),
 3: ('fail', 'only integer time deltas', 'recent select m, y, q @ y-3:1.234'),
 4: ('pass', '', 'recent top 3 @ m'),
 5: ('pass', '', 'verbose recent top 17 @COL d-30:10 @MOD m-3'),
 6: ('pass', '', 'select roger'),
 7: ('pass', '', 'select a_col'),
 8: ('pass', '', 'select a_col2, b_col'),
 9: ('pass', '', 'select *'),
 10: ('pass', '', 'top 10 select *'),
 11: ('pass', '', 'where year == 2024'),
 12: ('pass', '', 'where year == "2024"'),
 13: ('pass', '', 'where type == "book"'),
 14: ('pass', '', 'where price <= 12.50'),
 15: ('pass', '', '! Delbaen'),
 16: ('pass', '', '! /Wang, R/ and journal ~ Annals'),
 17: ('pass', '', 'recent top 3 author ~ /Wang, R/'),
 18: ('pass', '', 'select journal author ~ /Wang, R/'),
 19: ('pass', '', 'verbose top 4 recent select journal author ~ /Wang, R/'),
 20: ('pass', '', 'top 5 select journal author ~ /Wang, R/'),
 21: ('pass', '', 'sort by journal'),
 22: ('pass', '', 'order by journal, -year'),
 23: ('pass', '', 'order by journal, -year'),
 24: ('pass', 'changing top ok but warning', 'top 6 top 26 sort by journal'),
 25: ('pass', '', 'top 7 sort by -journal'),
 26: ('pass', '', 'top 8 order by author, journal, year'),
 27: ('pass', '', 'top 9 select journal where year == 2024 order by author'),
 28: ('pass',
      '',
      'verbose top 10 select journal where year == 2024 order by -journal, '
      'author'),
 29: ('pass',
      '',
      'recent top 14  verbose select *, -c ! /Wang, R/ and journal ~ /[A-J]+/ '
      'where year == 2024 and publisher ==  "Springer" and mod > 2024'),
 30: ('pass',
      '',
      'recent top 15  verbose select *, -c ! /Wang, R/ and journal ~ [A-J]+ '
      'where year == 2024 and publisher ==  "Springer" and mod > "2024-05"'),
 31: ('pass',
      '',
      'recent top 20  verbose select *, -c ! /Wang, R/ and journal ~ [A-J]+ '
      'where year == 2024 and publisher ==  "Springer" and mod > 2024-05'),
 32: ('pass',
      '',
      'recent top 21  verbose select *, -c ! /Wang, R/ and journal ~ [A-J]+ '
      'where year == 2024 and publisher ==  "Springer" and mod > "2024-05"'),
 33: ('pass',
      '',
      'top 30 select c, d, -a, e recent ! /Wang, R/ and journal ~ [A-J]+ where '
      'year == 2024 and publisher ==  "Springer" and mod > 2024 order by name, '
      'year'),
 34: ('fail', 'obvious error', 'error'),
 35: ('pass',
      '',
      'top 40 recent where age > 30 name ~ /^A/  @ y # alice amsterdam'),
 36: ('pass', '', 'recent top 50 where author == "Wang" !Ruodu # fuzzy term'),
 37: ('pass',
      'odd order',
      'where price > 10.5 select *, -id top 20 order by price'),
 38: ('pass',
      'odd order',
      'order by -modified, created verbose recent select path where size > '
      '1000'),
 39: ('pass',
      'odd order',
      "select name, id recent where type == 'user' top 50"),
 40: ('pass',
      'odd order, unquoted regex',
      'author ~ Smith order by name select *'),
 41: ('pass', 'cols vs keywords', 'select top, order, by, where, select'),
 42: ('pass',
      'cols vs keywords',
      'where top == 1 and sort == "asc" and by == "user"'),
 43: ('pass', 'cols vs keywords', 'select y, m, d, h order by q'),
 44: ('pass', 'cols vs keywords', 'where year > y and month > m'),
 45: ('pass',
      'complex where, regex, date',
      'where price >= -99.5 and price <= 21.25 and category != "sale" and name == "a name with '
      'spaces"'),
 46: ('pass',
      'complex where, regex, date',
      'where start_date > end_date and value > 0'),
 47: ('pass',
      'complex where, regex, date',
      '! /A/ and author ~ /B/ and title ~ /C/ and journal ~ /D/'),
 48: ('pass',
      'complex where, regex, date',
      '@created q-1 @modified w-2 @accessed d-3 @expires h-4'),
 49: ('pass',
      'complex where, regex, date',
      'select id, -name, created, -updated, path order by -created, path'),
 50: ('pass',
      'formatting, minimal',
      ' \t top   10 \n   select name, id \n where \t year==2025'),
 51: ('pass', 'formatting, minimal', '# just a fuzzy search string by itself'),
 52: ('pass', 'formatting, minimal', 'select name order by name'),
 53: ('pass', 'formatting, minimal', '@ d-0'),
 54: ('fail', 'single =', 'where value = 5'),
 55: ('fail', 'keyword for identifier', 'select name, where type == "book"'),
 56: ('fail', 'trailing comma', 'top 10 order by name,'),
 57: ('fail', 'non-numeric', '@ m-5:foo'),
 58: ('fail', 'parents in where clause', 'top 5 where year == 2025 and (name == joe or name == simon) @mod m-3:1')}

In [11]:
def run_tests(parser, test_dict, verbose=True):
    """
    Run parser tests on test_dict.

    test_dict = { (n, desc) -> test}
    
    """
    success = fail =  0
    for n, (expected, desc, query) in test_dict.items(): 
        try:
            if verbose: print(f"Query No. {n}\n{desc}")
            if verbose: print(f'{query = }\n')
            spec_dict = parser(query)
        except Exception as e:
            fail += 1
            if verbose or expected != 'fail':
                print(f'result: fail ({expected} expected) for query {n}: {query}')
        else:
            success += 1
            if verbose or expected != 'pass': 
                print(f'result: pass ({expected})\n')
            if verbose: pprint(spec_dict)
        if verbose: print('-'*40, end='\n\n')
    es = sum(i[0]=='pass' for i in test_dict.values())
    ef = len(test_dict) - es
    print(f'''
    SUMMARY:
    Pass    {success} vs expected {es}
    Fail    {fail} vs expected {ef}
    Total   {success+fail}
    Pct     {success / (success+fail):.0%}
    ''')

In [12]:
run_tests(parser, test_cases, False)

16:53:32.220|ERROR |querexfuzz.parser[parser.py:267 parser] Failed to parse query: 'recent select m, y, q @ y-3:1.234.
Error: Unexpected end-of-input. Expected one of:
	* DATE_UNIT
	* DATE_UNIT
	* DATE_UNIT

16:53:32.481|ERROR |querexfuzz.parser[parser.py:267 parser] Failed to parse query: 'error.
Error: Unexpected end-of-input. Expected one of:
	* TILDE

16:53:32.669|ERROR |querexfuzz.parser[parser.py:267 parser] Failed to parse query: 'where value = 5.
Error: No terminal matches '=' in the current parser context, at line 1 col 13

where value = 5
            ^
Expected one of:
	* EQ_TEST

16:53:32.674|ERROR |querexfuzz.parser[parser.py:267 parser] Failed to parse query: 'select name, where type == "book".
Error: No terminal matches '=' in the current parser context, at line 1 col 25

select name, where type == "book"
                        ^
Expected one of:
	* TILDE

16:53:32.679|ERROR |querexfuzz.parser[parser.py:267 parser] Failed to parse query: 'top 10 order by name,.
Error: Unexpected end-of-input. Expected one of:
	* MINUS
	* IDENTIFIER

16:53:32.685|ERROR |querexfuzz.parser[parser.py:267 parser] Failed to parse query: '@ m-5:foo.
Error: Unexpected end-of-input. Expected one of:
	* DATE_UNIT
	* DATE_UNIT
	* DATE_UNIT

16:53:32.690|ERROR |querexfuzz.parser[parser.py:267 parser] Failed to parse query: 'top 5 where year == 2025 and (name == joe or name == simon) @mod m-3:1.
Error: No terminal matches '(' in the current parser context, at line 1 col 30

top 5 where year == 2025 and (name == joe or name == simon) @mod m-3:
                             ^
Expected one of:
	* TILDE
	* IDENTIFIER

    SUMMARY:
    Pass    52 vs expected 52
    Fail    7 vs expected 7
    Total   59
    Pct     88%

In [ ]:
run_tests(parser, test_cases, True)

In [13]:
# parser(test_cases[45][2])
parser('where price >= -99.5')

{'select': {'include': [], 'exclude': []},
 'sort': [],
 'regex': [],
 'where': 'price >= -99.5',
 'top': -1,
 'flags': [],
 'dates': [],
 'fuzzy': None}

In [14]:
parser(" ! /[ae]{2,}/ and version ~ [a-e]{5} ")

{'select': {'include': [], 'exclude': []},
 'sort': [],
 'regex': [('BANG', '[ae]{2,}'), ('version', '[a-e]{5}')],
 'where': None,
 'top': -1,
 'flags': [],
 'dates': [],
 'fuzzy': None}

# Simple example

In [15]:
# 1. Create a sample DataFrame
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'age': [25, 30, 35, 40, 45],
    'city': ['Amsterdam', 'Berlin', 'Copenhagen', 'Berlin', 'Amsterdam'],
    'registered_date': pd.to_datetime(['2025-08-10', '2025-06-15', '2024-01-20', '2025-08-25', '2025-07-30'])
}
df = pd.DataFrame(data)
df

      name  age        city registered_date
0    Alice   25   Amsterdam      2025-08-10
1      Bob   30      Berlin      2025-06-15
2  Charlie   35  Copenhagen      2024-01-20
3    David   40      Berlin      2025-08-25
4      Eve   45   Amsterdam      2025-07-30

In [24]:
# 2. Initialize Querexfuzz with your config file
# (Ensure config.yml is in the same directory or provide the correct path)
qflex_engine = Querexfuzz(config_path='config.yaml')
qflex_engine.config

QuerexfuzzConfig(base_cols=['name', 'city', 'registered_date', 'age'], bang_field='name', date_fields=['registered_date'], default_date_field='registered_date', recent_field='registered_date', fuzzy=FuzzyConfig(fields=['name', 'city'], limit=50, score_col_name='score', highlight=True))

In [25]:
# 3. Attach the .querexfuzz method to your DataFrame
df = qflex_engine.attach_to(df)

In [26]:
# 4. Run queries!
print("--- People from Berlin ---")
df.querexfuzz("where city == 'Berlin'")

--- People from Berlin ---

    name    city registered_date  age
1    Bob  Berlin      2025-06-15   30
3  David  Berlin      2025-08-25   40

In [27]:
print("\n--- Recently registered (last 1 month) ---")
df.querexfuzz("recent @m-1")

--- Recently registered (last 1 month) ---

    name       city registered_date  age
3  David     Berlin      2025-08-25   40
0  Alice  Amsterdam      2025-08-10   25
4    Eve  Amsterdam      2025-07-30   45

In [28]:
# same without number
df.querexfuzz("recent @m")

    name       city registered_date  age
3  David     Berlin      2025-08-25   40
0  Alice  Amsterdam      2025-08-10   25
4    Eve  Amsterdam      2025-07-30   45

In [29]:
print("\n--- Less recently registered (last 24 months but more than 4) ---")
df.querexfuzz("recent @m-24:4")

--- Less recently registered (last 24 months but more than 4) ---

      name        city registered_date  age
2  Charlie  Copenhagen      2024-01-20   35

In [30]:
print("\n--- Fuzzy search for 'am', sorted by score ---")
df.querexfuzz("# am")

--- Fuzzy search for 'am', sorted by score ---

    name       city registered_date  age  score
0  Alice  Amsterdam      2025-08-10   25     41
4    Eve  Amsterdam      2025-07-30   45     41

In [31]:
print("\n--- Complex query: top 1 from Berlin older than 35, select name and age ---")
df.querexfuzz("top 1 where city == 'Berlin' and age > 35 select name, age")

--- Complex query: top 1 from Berlin older than 35, select name and age ---

    name    city registered_date  age
3  David  Berlin      2025-08-25   40

In [32]:
print("\n--- Bang query: names with a and e ! /[ae]{2,}/ ---")
df.querexfuzz(" ! [ae].*[ae]  ")

--- Bang query: names with a and e ! /[ae]{2,}/ ---

      name        city registered_date  age
0    Alice   Amsterdam      2025-08-10   25
2  Charlie  Copenhagen      2024-01-20   35
4      Eve   Amsterdam      2025-07-30   45