# `querexfuzz` project 

## Testing on a larger dataframe

## Provenance
* Branch off example: 2025-08-28

In [31]:
# separate startup from here
%load_ext autotime
%load_ext IPython.extensions.autoreload
%autoreload 2
import logging 
import yaml 
from pathlib import Path

def setup_logging(config_path):
    with config_path.open("r") as f:
        config = yaml.safe_load(f)
        logging.config.dictConfig(config)

setup_logging(Path("logconfig.yaml"))

from skimmatch import FuzzyMatcherMultiHi
from greater_tables.core import GT
from greater_tables.fabrications import quick_fab
from querexfuzz.config import FuzzyConfig
from querexfuzz import Querexfuzz, querexfuzz_from_df
import querexfuzz.dates as qfd
from functools import partial
fGT = partial(GT,  default_date_str="%Y-%m-%d %H:%M:%S.%f", 
             max_table_inch_width=12, table_font_pt_size=9,
             tikz=False)

The autotime extension is already loaded. To reload it, use:
  %reload_ext autotime
The IPython.extensions.autoreload extension is already loaded. To reload it, use:
  %reload_ext IPython.extensions.autoreload
time: 776 ms (started: 2025-08-28 19:00:36 +01:00)

In [2]:
# a larger dataframe
col_names = ['name', 'bio', 'size', 'number', 'accessed', 'create', 'mod', 'omit']
testdf = quick_fab(rows=10000, data_spec='ss20fidddi', 
                   metric_name_spec=col_names
                  )
fGT(testdf.head(2))

GT(df_id=TP4XUVVCHY4ZK)

time: 1.47 s (started: 2025-08-28 17:37:27 +01:00)

In [3]:
# default and helper 
qq = querexfuzz_from_df(testdf, bang_field='name', recent_field='mod', fuzzy_fields=['bio'])
qq.config

QuerexfuzzConfig(base_cols=['name', 'bio', 'size', 'number', 'accessed', 'create', 'mod', 'omit'], bang_field='name', date_fields=['accessed', 'create', 'mod'], default_date_field='mod', recent_field='mod', fuzzy=FuzzyConfig(fields=['bio'], limit=50, score_col_name='score', highlight=True))

time: 476 ms (started: 2025-08-28 17:37:45 +01:00)

In [12]:
fGT(testdf.q('top 10 select name, bio, number, -create, -mod, -accessed # waist'))

GT(df_id=TI6UKUQJC5VJG)

time: 1.83 s (started: 2025-08-28 18:50:41 +01:00)

In [14]:
testdf.index.is_unique

True

time: 444 ms (started: 2025-08-28 18:52:05 +01:00)

In [10]:
fGT(testdf.q('recent top 10 select name, bio, number, -create, -mod, -accessed # waist'))

GT(df_id=TZ3VJR63PGNYA)

time: 1.21 s (started: 2025-08-28 17:39:13 +01:00)

In [11]:
fGT(testdf.q('recent top 10 select name, bio, number, -create, -mod, -accessed bio ~ /\\bwaist\\b/'))

GT(df_id=T2IIJXJEG5O23)

time: 840 ms (started: 2025-08-28 17:39:18 +01:00)

In [25]:
fGT(testdf.q('order by -create top 3 select -bio, -accessed, -mod'), default_date_str="%Y-%m-%d %H:%M:%S.%f")

GT(df_id=TLTA6QITUTG2T)

time: 529 ms (started: 2025-08-28 18:57:26 +01:00)

In [27]:
# omit appears
fGT(testdf.q('order by -mod top 3 select *, -bio, -accessed, -mod'), default_date_str="%Y-%m-%d")

GT(df_id=TDRWOOW6DASHO)

time: 506 ms (started: 2025-08-28 18:58:57 +01:00)

In [28]:
fGT(testdf.q('order by -mod top 3 select *, -bio'), default_date_str="%Y-%m-%d")

GT(df_id=T53IDV7T3FICJ)

time: 943 ms (started: 2025-08-28 18:59:07 +01:00)

In [34]:
f = fGT(testdf.q('order by -mod top 3 select *, -bio where i_0 == "sanitary"'), default_date_str="%Y-%m-%d")
f

GT(df_id=TSSAEYH2BEKBA)

time: 579 ms (started: 2025-08-28 19:00:54 +01:00)

In [36]:
print(f.html[:100])

<div class="greater-table">
<style>
    #TSSAEYH2BEKBA  {
    border-collapse: collapse;
    font-fa
time: 714 ms (started: 2025-08-28 19:01:21 +01:00)

In [30]:
# index workes in query but not in regex
fGT(testdf.q('order by -mod top 3 select *, -bio  i_0 ~ sanitary'), default_date_str="%Y-%m-%d")

ValueError: Invalid column for regex search: 'i_0'

time: 494 ms (started: 2025-08-28 18:59:47 +01:00)

## Incomplete `config` leading to warnings

In [20]:
qwarn = Querexfuzz(base_cols=['name', 'bio', 'size', 'number', 'accessed', 'create', 'mod'], bang_field=None, date_fields=['accessed', 'create', 'mod'], default_date_field=None, recent_field=None, fuzzy=FuzzyConfig(fields=[], limit=50, score_col_name='score', highlight=True))
testdf = qwarn.attach_to(testdf, 'qw')

time: 461 ms (started: 2025-08-28 18:56:12 +01:00)

In [22]:
testdf.qw('recent top 10')

<string>:70: QuerexfuzzConfigurationWarning: No valid recent field - recent sort ignored.

metric,name,bio,size,number,accessed,create,mod
i_0,,,,,,,
boring,dieter,detect mischief satirical barring bones enforc...,133873.076949,563946,2021-03-28 21:20:03.262069248,2024-08-06 21:46:24.250618112,2023-04-25 07:15:52.802040320
mend,postmaster,troop division sandbagging marvel fleeing sale...,19272.062066,279285,2020-10-19 12:09:53.235994880,2025-02-15 10:36:47.930402048,2018-03-04 00:56:31.826437376
liberalizing,nurtured,ironies others jeremy delights slash antitrust...,116135.190596,311869,2020-07-06 15:06:00.850191360,2025-04-13 11:38:14.418176512,2017-11-13 15:28:38.581660928
broadband,tartan,abides holler georgia picker scape misrepresen...,546084.674530,337025,2020-09-26 13:19:34.531637248,2024-06-04 03:00:57.841122560,2021-02-08 09:32:09.062701056
entertained,framing,tramp slavic grief books cora suspicious beard...,-82271.385774,630329,2023-10-20 08:12:15.003686656,2025-06-04 13:41:52.551879680,2017-02-24 21:29:56.220975616
teases,laying,correspond unavailing blindly allay spooky con...,-122799.771448,369927,2020-03-14 12:58:15.444030208,2024-03-25 16:37:06.702760960,2025-08-02 18:50:44.462490112
lake,handedness,plotted settle melted distances flowed malay p...,506485.035926,773677,2020-06-24 11:55:39.726379776,2025-08-04 00:39:08.691333888,2015-12-09 20:19:51.349629952
ports,telford,complicated connie effortless packages radical...,-155607.841408,722956,2020-06-17 20:12:24.223465472,2025-05-31 18:20:04.275533056,2022-03-07 05:44:48.525258752
formed,forte,diagnosing scoot demise rainy preparers infusi...,-42008.107015,254275,2021-07-12 02:32:32.609949440,2024-09-28 23:56:43.389819904,2023-03-07 18:33:12.578437376
hook,preferential,simultaneous contracting freeing oldest canton...,123998.534356,690651,2024-09-27 02:01:22.598773248,2024-01-31 05:42:51.382019840,2018-07-29 12:34:14.298725376

time: 452 ms (started: 2025-08-28 18:56:31 +01:00)

In [24]:
testdf.qw('recent top 5 # waist')

<string>:33: QuerexfuzzConfigurationWarning: No valid field for fuzzy search - ignoring pattern.
<string>:70: QuerexfuzzConfigurationWarning: No valid recent field - recent sort ignored.

metric,name,bio,size,number,accessed,create,mod
i_0,,,,,,,
boring,dieter,detect mischief satirical barring bones enforc...,133873.076949,563946,2021-03-28 21:20:03.262069248,2024-08-06 21:46:24.250618112,2023-04-25 07:15:52.802040320
mend,postmaster,troop division sandbagging marvel fleeing sale...,19272.062066,279285,2020-10-19 12:09:53.235994880,2025-02-15 10:36:47.930402048,2018-03-04 00:56:31.826437376
liberalizing,nurtured,ironies others jeremy delights slash antitrust...,116135.190596,311869,2020-07-06 15:06:00.850191360,2025-04-13 11:38:14.418176512,2017-11-13 15:28:38.581660928
broadband,tartan,abides holler georgia picker scape misrepresen...,546084.674530,337025,2020-09-26 13:19:34.531637248,2024-06-04 03:00:57.841122560,2021-02-08 09:32:09.062701056
entertained,framing,tramp slavic grief books cora suspicious beard...,-82271.385774,630329,2023-10-20 08:12:15.003686656,2025-06-04 13:41:52.551879680,2017-02-24 21:29:56.220975616

time: 460 ms (started: 2025-08-28 18:56:50 +01:00)

In [ ]:
fGT(testdf.q('order by -create top 3 select -bio, -accessed, -mod'), default_date_str="%m-%d @ %H:%M")

In [ ]:
testdf.q(' ! ^healt  ')

In [ ]:
fGT(testdf.q('top 10 # health'), default_date_str="%m-%d @ %H:%M")

In [ ]:
Querexfuzz.parse('top 10 # health')

In [ ]:
qfz = Querexfuzz(
    base_cols=col_names[:-1], 
    date_fields=['date'], 
    default_date_field='date', 
    bang_field='name', 
    recent_field='date', 
    fuzzy=FuzzyConfig(fields=['bio'], limit=50, score_col_name='score'))

In [ ]:
testdf = qfz.attach_to(testdf)

In [ ]:
fGT(testdf.q('select score top 10 #ribbons spank'))

In [ ]:
fGT(testdf.q('top 10 # health'))

In [ ]:
testdf.q('select *, -bio top 10 recent where size > 0 ! ^h @y-2')

In [ ]:
testdf.q('select * top 5 recent ! ^[abc]{2,} ')

In [ ]:
testdf.q('select * top 5 recent where name == "healthy"')

In [ ]:
fGT(quick_fab(20, 'dddd'), default_date_str="%Y-%m")